config/routes.rb
Vervootest2::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "vervoom/home"
  get "vervoom/challenges"
  get "vervoom/users"
  get "vervoom/sponsors"
  get "vervoom/nonprofits"

  resources :roles
  resources :sponsors
  resources :nonprofits

  resources :challenges do
    put '/add_sponsor', to: 'challenges#add_sponsor', as: 'add_sponsor'
    put '/add_nonprofit', to: 'challenges#add_nonprofit', as: 'add_nonprofit'
    put '/remove_sponsor/:id', to: 'challenges#remove_sponsor', as: 'remove_sponsor'
    put '/remove_nonprofit/:id', to: 'challenges#remove_nonprofit', as: 'remove_nonprofit'
    get '/analytics', to: 'challenges#analytics', as: 'analytics'
    get :autocomplete_location_name, :on => :collection
    get :autocomplete_topic_name, :on => :collection

    resources :action_stubs, except: [:index, :create]
    resources :action_scavengers, only: [:create, :update] do
      resources :scavenger_items, except: [:index, :show] do
        put '/add_prereq', to: 'scavenger_items#add_prereq', as: 'add_prereq'
        put '/remove_prereq/:id', to: 'scavenger_items#remove_prereq', as: 'remove_prereq'
        get '/showqr', to: 'scavenger_items#showqr', as: 'showqr'
      end
    end
    resources :action_simpleshares, only: [:create, :update]
  end

  devise_for :users, skip: [:registrations, :passwords]


  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    delete '/signout' => 'devise/sessions#destroy', as: :signout
    get 'users/edit' => 'devise/registrations#edit', :as => 'profile'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users, only: [:index, :new, :show, :create, :destroy]

  root :to => "vervoom#home"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/action_scavenger.rb
class ActionScavenger < ActiveRecord::Base
  acts_as :action_stub

  has_many :scavenger_items, :dependent => :destroy
  accepts_nested_attributes_for :scavenger_items, :reject_if => lambda { |a| a[:hint_msg].blank?  }, :allow_destroy => true
  # OR a[:find_amt]?
end

app/models/action_simpleshare.rb
class ActionSimpleshare < ActiveRecord::Base
  acts_as :action_stub
end

app/models/action_stub.rb
class ActionStub < ActiveRecord::Base
  acts_as_superclass

  belongs_to :challenge
  has_many :user_activity_trackings, :foreign_key  => "activity_id"

  def action_type
    return 'scavenger' if self.as_action_stub_type == 'ActionScavenger'
    return 'simpleshare' if self.as_action_stub_type == 'ActionSimpleshare'
  end
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  has_many :action_stubs, :dependent => :destroy

  has_and_belongs_to_many :nonprofits
  has_and_belongs_to_many :sponsors

  belongs_to :owner, :class_name => 'User', :foreign_key => "owner_id"
  # the 2 below are subject to delete .. not needed
  has_many :challenge_memberships
  has_many :users, through: :challenge_memberships
  has_one :web_challenge
  has_many :challenge_users

  has_attached_file :challenge_img
  has_attached_file  :img_thumb_url
  has_attached_file  :logo_url


  # validates_attachment_content_type :challenge_img, :content_type => /\Aimage\/.*\Z/
  # validates_attachment_content_type :img_thumb_url, :content_type => /\Aimage\/.*\Z/
  # validates_attachment_content_type :logo_url, :content_type => /\Aimage\/.*\Z/

  accepts_nested_attributes_for :action_stubs, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

  acts_as_taggable_on :locations, :topics
end

app/models/challenge_user.rb
class ChallengeUser < Statsdb
    self.table_name = 'challenge_users'
    belongs_to :challenge

end

app/models/nonprofit.rb
class Nonprofit < ActiveRecord::Base
  has_attached_file :image_full
  has_attached_file  :image_thumb

  has_and_belongs_to_many :challenges
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/scavenger_item.rb
class ScavengerItem < ActiveRecord::Base
  belongs_to :action_scavenger
  has_and_belongs_to_many :prereqs,
              class_name: "ScavengerItem",
              join_table: :scavenger_items_prereqs,
              foreign_key: :scavenger_item_id,
              association_foreign_key: :prereq_id
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_attached_file :image_full
  has_attached_file  :image_thumb

  has_and_belongs_to_many :challenges
end

app/models/statsdb.rb
class Statsdb < ActiveRecord::Base
  self.abstract_class = true
  establish_connection "stats_#{Rails.env}"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
         #:recoverable, :rememberable, :trackable, :validatable

  has_many :challenge_memberships
  has_many :challenges, through: :challenge_memberships
end

app/models/web_challenge.rb
class WebChallenge < Statsdb
    self.table_name = 'web_challenges'
    belongs_to :challenge

end

app/controllers/action_stubs_controller.rb
class ActionStubsController < ApplicationController
  before_action :set_action_stub, only: [:show, :edit, :update, :destroy]
  before_action :find_challenge, except: [:index]

  def show
    @action_type = @action_stub.action_type
  end

  def new
    @action_type = params[:action_type]
    @action_stub = generate_action_stub
  end

  def edit
    @action_type = @action_stub.action_type
  end

  def destroy
    @action_stub.destroy
    flash[:notice] = 'Action was successfully deleted'
    redirect_to challenge_path(@challenge)
  end

  private

    def set_action_stub
      @action_stub = ActionStub.find(params[:id])
    end

    def find_challenge
      @challenge ||= Challenge.find(params[:challenge_id])
    end

    def generate_action_stub
      if @action_type == 'simpleshare'
        @action_stub = ActionSimpleshare.new(challenge: @challenge)
      else
        @action_stub = ActionScavenger.new(challenge: @challenge)
      end
    end
end

app/helpers/action_bases_helper.rb
module ActionBasesHelper
end

app/helpers/action_stubs_helper.rb
module ActionStubsHelper
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_action_type(instance)
    instance.class.name.gsub("Action", "")
  end

  def action_type_collection
    [["Scavenger", "scavenger"], ["Simpleshare", "simpleshare"]]
  end

  def available_nonprofits
    collection = []

    Nonprofit.all.each do |nonprofit|
      collection << [nonprofit.name, nonprofit.id]
    end

    collection
  end

  def available_sponsors
    collection = []

    Sponsor.all.each do |nonprofit|
      collection << [nonprofit.name, nonprofit.id]
    end

    collection
  end

  def available_prereqs(action_scavenger, scavenger_item)
    collection = []
    # action_scavenger.scavenger_items.where(["prereq_id not in (?) and prereq_id != ?",scavenger_item.prereq_ids,scavenger_item.id]).each do |prereq|
    action_scavenger.scavenger_items.where(["id != ?",scavenger_item.id]).each do |prereq|
      collection << [(!prereq.name.blank? ? prereq.name : prereq.hint_msg ) , prereq.id]
    end

    collection
  end

end

app/helpers/challenges_helper.rb
module ChallengesHelper
    include ActsAsTaggableOn::TagsHelper
end

app/helpers/nonprofits_helper.rb
module NonprofitsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/vervoom_helper.rb
module VervoomHelper
end

app/views/action_stubs/_form.html.haml
- if @action_type == 'simpleshare'
  = render 'action_stubs/simpleshare_form'
- else
  = render 'action_stubs/scavenger_form'

app/views/action_stubs/_scavenger_detail.html.haml
%p#notice= notice
%p
  %strong Name:
  = @action_stub.name
%p
  %strong Description:
  = @action_stub.description
%p
  %strong Enabled:
  = @action_stub.enabled
%p
  %strong Sequential Reveal:
  = @action_stub.seqreveal_flag
%p
  %strong Challenge:
  = @action_stub.challenge_id
%p
  %strong Amt:
  = @action_stub.amt
%p
  %strong Team:
  = @action_stub.team
%p
  %strong Start Msg:
  = @action_stub.start_msg
%p
  %strong Complete Msg:
  = @action_stub.complete_msg

%br
.page-title
  %h2 Scavenger Items
  = link_to 'New Scavenger Item', new_challenge_action_scavenger_scavenger_item_path(@challenge, @action_stub.specific), class: 'btn btn-primary'

%table.table.table-striped
  %thead
    %tr
      %th Name/Hint Msg
      %th PreRequisites
      %th Order
      %th Find Amt
      %th

  %tbody
    - @action_stub.specific.scavenger_items.each do |item|
      %tr
        %td #{!item.name.blank? ? item.name : item.hint_msg}
        %td
          %table.table.table-striped
            %thead
              %tr
                %th
                  =form_tag(challenge_action_scavenger_scavenger_item_add_prereq_path(@challenge, @action_stub.specific.id, item), method: 'put', id: 'add-prereq', class: 'form-inline') do
                    = select_tag 'prereq_id', options_for_select(available_prereqs(@action_stub.specific,item)), prompt: 'Select PreReq', class: 'form-control'
                    = submit_tag 'Add', class: 'btn btn-primary'
            %tbody
              - item.prereqs.each do |preqitem|
                %tr
                  %td #{!preqitem.name.blank? ? preqitem.name : preqitem.hint_msg}
                  %td
                    = link_to 'remove', challenge_action_scavenger_scavenger_item_remove_prereq_path(@challenge, @action_stub.specific, item,preqitem), method: :put, 'data-confirm' =>   "Are you sure you want to remove #{preqitem.name} from this item?"
        %td= item.order
        %td= item.find_amt
        %td
          = link_to 'Edit', edit_challenge_action_scavenger_scavenger_item_path(@challenge, @action_stub.specific, item)
          |
          = link_to 'Destroy', challenge_action_scavenger_scavenger_item_path(@challenge, @action_stub.specific, item), method: :delete, data: { confirm: 'Are you sure?' }
          |
          = link_to 'QR Code', challenge_action_scavenger_scavenger_item_showqr_path(@challenge, @action_stub.specific, item)


= link_to 'Edit', edit_challenge_action_stub_path(@challenge, @action_stub)
|
\#{link_to 'Back', challenge_path(@challenge)}

app/views/action_stubs/_scavenger_form.html.haml
= form_for([@challenge, @action_stub.specific]) do |f|
  - if @action_stub.errors.any?
    #error_explanation
      %h2
        = pluralize(@action_stub.errors.count, "error")
        prohibited this action_stub from being saved:
      %ul
        - @action_stub.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :enabled
    %br/
    = f.check_box :enabled
  .field
    = f.label :seqreveal_flag
    %br/
    = f.check_box :seqreveal_flag
  .field
    = f.label :amt
    %br/
    = f.text_field :amt

  .field
    = f.label :start_msg
    %br/
    = f.text_field :start_msg

  .field
    = f.label :complete_msg
    %br/
    = f.text_field :complete_msg

  .field
    = f.label :team
    %br/
    = f.check_box :team

  .actions
    = f.submit

app/views/action_stubs/_simpleshare_detail.html.haml
%p#notice= notice
%p
  %strong Name:
  = @action_stub.name
%p
  %strong Description:
  = @action_stub.description
%p
  %strong Enabled:
  = @action_stub.enabled
%p
  %strong Challenge:
  = @action_stub.challenge_id
%p
  %strong Amt:
  = @action_stub.amt
%p
  %strong Display Msg:
  = @action_stub.display_msg
%p
  %strong Network Filter List:
  = @action_stub.network_filter_list

= link_to 'Edit', edit_challenge_action_stub_path(@challenge, @action_stub)
|
\#{link_to 'Back', challenge_path(@challenge)}

app/views/action_stubs/_simpleshare_form.html.haml
= form_for([@challenge, @action_stub.specific]) do |g|
  - if @action_stub.errors.any?
    #error_explanation
      %h2
        = pluralize(@action_stub.errors.count, "error")
        prohibited this action_stub from being saved:
      %ul
        - @action_stub.errors.full_messages.each do |msg|
          %li= msg
  .field
    = g.label :name
    %br/
    = g.text_field :name
  .field
    = g.label :description
    %br/
    = g.text_area :description
  .field
    = g.label :enabled
    %br/
    = g.check_box :enabled
  .field
    = g.label :amt
    %br/
    = g.text_field :amt

  .field
    = g.label :display_msg
    %br/
    = g.text_field :display_msg

  .field
    = g.label :network_filter_list
    %br/
    = g.text_field :network_filter_list


  .actions
    = g.submit

app/views/action_stubs/edit.html.haml
%h1 
  Edit
  = format_action_type(@action_stub.specific)
  Action

= render 'form'
#{link_to 'Back', challenge_path(@challenge)}

app/views/action_stubs/index.html.haml
%h1 Listing action_stubs
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Enabled
      %th Challenge
      %th Amt
      %th
      %th
      %th
  %tbody
    - @action_stubs.each do |action_stub|
      %tr
        %td= action_stub.name
        %td= action_stub.description
        %td= action_stub.enabled
        %td= action_stub.challenge_id
        %td= action_stub.amt
        %td= link_to 'Show', action_stub
        %td= link_to 'Edit', edit_action_stub_path(action_stub)
        %td= link_to 'Destroy', action_stub, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Action stub', new_action_stub_path

app/views/action_stubs/new.html.haml
%h1
  New
  = format_action_type(@action_stub)
  Action
= render 'form'
= link_to 'Back', challenge_path(@challenge)

app/views/action_stubs/show.html.haml
- if @action_type == 'simpleshare'
  = render 'action_stubs/simpleshare_detail'
- else
  = render 'action_stubs/scavenger_detail'