config/routes.rb
Vervootest2::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "vervoom/home"
  get "vervoom/challenges"
  get "vervoom/users"
  get "vervoom/sponsors"
  get "vervoom/nonprofits"

  resources :roles
  resources :sponsors
  resources :nonprofits

  resources :challenges do
    put '/add_sponsor', to: 'challenges#add_sponsor', as: 'add_sponsor'
    put '/add_nonprofit', to: 'challenges#add_nonprofit', as: 'add_nonprofit'
    put '/remove_sponsor/:id', to: 'challenges#remove_sponsor', as: 'remove_sponsor'
    put '/remove_nonprofit/:id', to: 'challenges#remove_nonprofit', as: 'remove_nonprofit'
    get '/analytics', to: 'challenges#analytics', as: 'analytics'
    get :autocomplete_location_name, :on => :collection
    get :autocomplete_topic_name, :on => :collection

    resources :action_stubs, except: [:index, :create]
    resources :action_scavengers, only: [:create, :update] do
      resources :scavenger_items, except: [:index, :show] do
        put '/add_prereq', to: 'scavenger_items#add_prereq', as: 'add_prereq'
        put '/remove_prereq/:id', to: 'scavenger_items#remove_prereq', as: 'remove_prereq'
        get '/showqr', to: 'scavenger_items#showqr', as: 'showqr'
      end
    end
    resources :action_simpleshares, only: [:create, :update]
  end

  devise_for :users, skip: [:registrations, :passwords]


  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    delete '/signout' => 'devise/sessions#destroy', as: :signout
    get 'users/edit' => 'devise/registrations#edit', :as => 'profile'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users, only: [:index, :new, :show, :create, :destroy]

  root :to => "vervoom#home"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/action_scavenger.rb
class ActionScavenger < ActiveRecord::Base
  acts_as :action_stub

  has_many :scavenger_items, :dependent => :destroy
  accepts_nested_attributes_for :scavenger_items, :reject_if => lambda { |a| a[:hint_msg].blank?  }, :allow_destroy => true
  # OR a[:find_amt]?
end

app/models/action_simpleshare.rb
class ActionSimpleshare < ActiveRecord::Base
  acts_as :action_stub
end

app/models/action_stub.rb
class ActionStub < ActiveRecord::Base
  acts_as_superclass

  belongs_to :challenge
  has_many :user_activity_trackings, :foreign_key  => "activity_id"

  def action_type
    return 'scavenger' if self.as_action_stub_type == 'ActionScavenger'
    return 'simpleshare' if self.as_action_stub_type == 'ActionSimpleshare'
  end
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  has_many :action_stubs, :dependent => :destroy

  has_and_belongs_to_many :nonprofits
  has_and_belongs_to_many :sponsors

  belongs_to :owner, :class_name => 'User', :foreign_key => "owner_id"
  # the 2 below are subject to delete .. not needed
  has_many :challenge_memberships
  has_many :users, through: :challenge_memberships
  has_one :web_challenge
  has_many :challenge_users

  has_attached_file :challenge_img
  has_attached_file  :img_thumb_url
  has_attached_file  :logo_url


  # validates_attachment_content_type :challenge_img, :content_type => /\Aimage\/.*\Z/
  # validates_attachment_content_type :img_thumb_url, :content_type => /\Aimage\/.*\Z/
  # validates_attachment_content_type :logo_url, :content_type => /\Aimage\/.*\Z/

  accepts_nested_attributes_for :action_stubs, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

  acts_as_taggable_on :locations, :topics
end

app/models/challenge_user.rb
class ChallengeUser < Statsdb
    self.table_name = 'challenge_users'
    belongs_to :challenge

end

app/models/nonprofit.rb
class Nonprofit < ActiveRecord::Base
  has_attached_file :image_full
  has_attached_file  :image_thumb

  has_and_belongs_to_many :challenges
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/scavenger_item.rb
class ScavengerItem < ActiveRecord::Base
  belongs_to :action_scavenger
  has_and_belongs_to_many :prereqs,
              class_name: "ScavengerItem",
              join_table: :scavenger_items_prereqs,
              foreign_key: :scavenger_item_id,
              association_foreign_key: :prereq_id
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_attached_file :image_full
  has_attached_file  :image_thumb

  has_and_belongs_to_many :challenges
end

app/models/statsdb.rb
class Statsdb < ActiveRecord::Base
  self.abstract_class = true
  establish_connection "stats_#{Rails.env}"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable
         #:recoverable, :rememberable, :trackable, :validatable

  has_many :challenge_memberships
  has_many :challenges, through: :challenge_memberships
end

app/models/web_challenge.rb
class WebChallenge < Statsdb
    self.table_name = 'web_challenges'
    belongs_to :challenge

end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_action_type(instance)
    instance.class.name.gsub("Action", "")
  end

  def action_type_collection
    [["Scavenger", "scavenger"], ["Simpleshare", "simpleshare"]]
  end

  def available_nonprofits
    collection = []

    Nonprofit.all.each do |nonprofit|
      collection << [nonprofit.name, nonprofit.id]
    end

    collection
  end

  def available_sponsors
    collection = []

    Sponsor.all.each do |nonprofit|
      collection << [nonprofit.name, nonprofit.id]
    end

    collection
  end

  def available_prereqs(action_scavenger, scavenger_item)
    collection = []
    # action_scavenger.scavenger_items.where(["prereq_id not in (?) and prereq_id != ?",scavenger_item.prereq_ids,scavenger_item.id]).each do |prereq|
    action_scavenger.scavenger_items.where(["id != ?",scavenger_item.id]).each do |prereq|
      collection << [(!prereq.name.blank? ? prereq.name : prereq.hint_msg ) , prereq.id]
    end

    collection
  end

end

app/helpers/challenges_helper.rb
module ChallengesHelper
    include ActsAsTaggableOn::TagsHelper
end

app/helpers/nonprofits_helper.rb
module NonprofitsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/vervoom_helper.rb
module VervoomHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Vervoo"
    = stylesheet_link_tag :application, :media => "all"
    = stylesheet_link_tag "application", "jquery-ui/jquery-ui.min"
    = yield :stylesheets


    = javascript_include_tag :application, "jquery-ui.min"
    = javascript_include_tag :application
    = yield :javascript
    = csrf_meta_tags
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      %nav.navbar-inner
        .container
          = render 'shared/navigation'
    #main{:role => "main"}
      .container
        .content
          = render 'shared/notifications'
          = yield
          %footer

app/views/shared/_navigation.html.haml
.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Vervoo', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li.active
          = link_to 'Home', root_path

      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          - if user_signed_in?
            %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
              = current_user.email
              %b.caret
            %ul.dropdown-menu.animated.fadeInRight
              %span.arrow.top
              %li
                = link_to 'Profile', profile_path
              %li
                = link_to 'Sign Out', signout_path, method: :delete
          - else
            = link_to 'Sign In', signin_path

app/views/shared/_notifications.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-message alert-#{name == :notice ? "success" : "danger"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}"