config/routes.rb
Vervootest2::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "vervoom/home"
  get "vervoom/challenges"
  get "vervoom/users"
  get "vervoom/sponsors"
  get "vervoom/nonprofits"

  resources :roles
  resources :sponsors
  resources :nonprofits

  resources :challenges do
    put '/add_sponsor', to: 'challenges#add_sponsor', as: 'add_sponsor'
    put '/add_nonprofit', to: 'challenges#add_nonprofit', as: 'add_nonprofit'
    put '/remove_sponsor/:id', to: 'challenges#remove_sponsor', as: 'remove_sponsor'
    put '/remove_nonprofit/:id', to: 'challenges#remove_nonprofit', as: 'remove_nonprofit'
    get '/analytics', to: 'challenges#analytics', as: 'analytics'
    get :autocomplete_location_name, :on => :collection
    get :autocomplete_topic_name, :on => :collection

    resources :action_stubs, except: [:index, :create]
    resources :action_scavengers, only: [:create, :update] do
      resources :scavenger_items, except: [:index, :show] do
        put '/add_prereq', to: 'scavenger_items#add_prereq', as: 'add_prereq'
        put '/remove_prereq/:id', to: 'scavenger_items#remove_prereq', as: 'remove_prereq'
        get '/showqr', to: 'scavenger_items#showqr', as: 'showqr'
      end
    end
    resources :action_simpleshares, only: [:create, :update]
  end

  devise_for :users, skip: [:registrations, :passwords]


  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    delete '/signout' => 'devise/sessions#destroy', as: :signout
    get 'users/edit' => 'devise/registrations#edit', :as => 'profile'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users, only: [:index, :new, :show, :create, :destroy]

  root :to => "vervoom#home"
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  has_many :action_stubs, :dependent => :destroy

  has_and_belongs_to_many :nonprofits
  has_and_belongs_to_many :sponsors

  belongs_to :owner, :class_name => 'User', :foreign_key => "owner_id"
  # the 2 below are subject to delete .. not needed
  has_many :challenge_memberships
  has_many :users, through: :challenge_memberships
  has_one :web_challenge
  has_many :challenge_users

  has_attached_file :challenge_img
  has_attached_file  :img_thumb_url
  has_attached_file  :logo_url


  # validates_attachment_content_type :challenge_img, :content_type => /\Aimage\/.*\Z/
  # validates_attachment_content_type :img_thumb_url, :content_type => /\Aimage\/.*\Z/
  # validates_attachment_content_type :logo_url, :content_type => /\Aimage\/.*\Z/

  accepts_nested_attributes_for :action_stubs, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

  acts_as_taggable_on :locations, :topics
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]
  autocomplete :location, :name, :class_name => 'ActsAsTaggableOn::Tag'
  autocomplete :topic, :name, :class_name => 'ActsAsTaggableOn::Tag'
  def index
    @challenges = Challenge.all
  end

  def show
    @challenge = Challenge.find(params[:id])
  end

  def analytics

    @challenge = Challenge.find(params[:challenge_id])

  end

  def new
    @challenge = Challenge.new
    action_stub= @challenge.action_stubs.build
  end

  def edit
    action_stub= @challenge.action_stubs.build
  end

  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @challenge }
      else
        format.html { render action: 'new' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_nonprofit
    @challenge = Challenge.where(id: params[:challenge_id]).first
    @nonprofit = Nonprofit.where(id: params[:nonprofit_id]).first

    return missing_option_error unless params[:nonprofit_id].present?

    if @nonprofit
      return already_added_error(@nonprofit) if @challenge.nonprofits.include?(@nonprofit)
      @challenge.nonprofits << @nonprofit
      @challenge.save!

      flash[:notice] = "#{@nonprofit.name} was successfully added to this challenge"
      redirect_to challenge_path(@challenge)
    else
      flash.now[:alert] = 'There was an error adding this nonprofit to the challenge'
      render :show
    end
  end

  def remove_nonprofit
    @challenge = Challenge.where(id: params[:challenge_id]).first
    @nonprofit = Nonprofit.where(id: params[:id]).first

    if @nonprofit
      @challenge.nonprofits.delete(@nonprofit)
      flash[:notice] = "#{@nonprofit.name} has been removed from the challenge."
      redirect_to challenge_path(@challenge)
    else
      flash.now[:alert] = 'The nonprofit could not be found'
    end
  end

  def add_sponsor
    @challenge = Challenge.where(id: params[:challenge_id]).first
    @sponsor = Sponsor.where(id: params[:sponsor_id]).first

    return missing_option_error unless params[:sponsor_id].present?

    if @sponsor
      return already_added_error(@sponsor) if @challenge.sponsors.include?(@sponsor)

      @challenge.sponsors << @sponsor
      @challenge.save!

      flash[:notice] = "#{@sponsor.name} was successfully added to this challenge"
      redirect_to challenge_path(@challenge)
    else
      flash.now[:alert] = 'There was an error adding this sponsor to the challenge'
      render :show
    end
  end

  def remove_sponsor
    @challenge = Challenge.where(id: params[:challenge_id]).first
    @sponsor = Sponsor.where(id: params[:id]).first

    if @sponsor
      @challenge.sponsors.delete(@sponsor)
      flash[:notice] = "#{@sponsor.name} has been removed from the challenge."
      redirect_to challenge_path(@challenge)
    else
      flash.now[:alert] = 'The sponsor could not be found'
    end
  end

  def tag_cloud
    @tags = Challenge.tag_counts_on(:tags)
  end

  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url }
      format.json { head :no_content }
    end
  end

  private
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    def already_added_error(resource)
      flash.now[:alert]= "#{resource.name} has already been added to this Challenge."
      render :show
    end

    def missing_option_error
      flash.now[:alert]= "Please select an option."
      render :show
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:name, :description, :start_date, :end_date, :challenge_img, :total_offer, :amount_raised, :sponsor_blurb, :charity_blurb, :enabled, :seo_name, :img_thumb_url, :logo_url, :location_list,:topic_list)
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
    include ActsAsTaggableOn::TagsHelper
end

app/views/challenges/_action_stub_form.html.haml
%h2 New action
.field
  = f.label :name
  %br/
  = f.text_field :name
.field
  = f.label :description
  %br/
  = f.text_area :description
.field
  = f.label :enabled
  %br/
  = f.check_box :enabled
.field
  = f.label :amt
  %br/
  = f.text_field :amt

app/views/challenges/_action_stub_list.html.haml
%h1 Listing action_stubs
%table
  %thead
    %tr
      %th Name
      %th Enabled
      %th Amt
      %th Heir type
      %th
      %th
      %th
  %tbody
    - @action_stubs.each do |action_stub|
      %tr
        %td= action_stub.name
        %td= action_stub.enabled
        %td= action_stub.amt
        %td= link_to 'Show', action_stub
        %td= link_to 'Edit', edit_action_stub_path(action_stub)
        %td= link_to 'Destroy', action_stub, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Action stub', new_action_stub_path

app/views/challenges/_form.html.haml
= form_for @challenge, :html => { :multipart => true }  do |f|
  - if @challenge.errors.any?
    #error_explanation
      %h2
        = pluralize(@challenge.errors.count, "error")
        prohibited this challenge from being saved:
      %ul
        - @challenge.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label 'Location Tags:'
    %br/
    = f.autocomplete_field :location_list, autocomplete_location_name_challenges_path, :"data-delimiter" => ', '
  .field
    = f.label 'Topic Tags:'
    %br/
    = f.autocomplete_field :topic_list, autocomplete_topic_name_challenges_path, :"data-delimiter" => ', '
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :start_date
    %br/
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    %br/
    = f.datetime_select :end_date
  .field
    = f.label :challenge_img
    %br/
    = f.file_field :challenge_img
  .field
    = f.label :img_thumb_url
    %br/
    = f.file_field :img_thumb_url
  .field
    = f.label :logo_url
    %br/
    = f.file_field :logo_url
  .field
    = f.label :total_offer
    %br/
    = f.text_field :total_offer
  .field
    = f.label :amount_raised
    %br/
    = f.text_field :amount_raised
  .field
    = f.label :sponsor_blurb
    %br/
    = f.text_area :sponsor_blurb
  .field
    = f.label :charity_blurb
    %br/
    = f.text_area :charity_blurb
  .field
    = f.label :enabled
    %br/
    = f.check_box :enabled
  .field
    = f.label :seo_name
    %br/
    = f.text_field :seo_name
  .actions
    = f.submit

app/views/challenges/analytics.html.haml
%p#notice= notice
%p
  %strong Name:
  = @challenge.name
%p
  %strong Total offer:
  = @challenge.total_offer
%p
  %strong Amount Raised:
  = @challenge.web_challenge.nil? ?  "no one signed up yet" : @challenge.web_challenge.amount_raised
%p
  %strong Start date:
  = @challenge.start_date
%p
  %strong End date:
  = @challenge.end_date



%br
= link_to 'Back to Challenges', challenges_path
%br

.row
  .col-md-12
    .page-title
      %h2 Action Logs
- @challenge.action_stubs.each do |action|
  .row
    .col-md-12
      %h3
        = action.name
        |
        = action.as_action_stub_type

      %table.table.table-striped
        %thead
          %tr
            %th Timestamp
            %th Activity Type
            %th Destination
            %th Amount
            %th Extra Info

          %tbody
            - action.user_activity_trackings.each do |logentry|
              %tr
                %td= logentry.tstamp
                %td= logentry.activity_sub_type
                %td= logentry.dest
                %td= logentry.amt
                %td= logentry.extra_info
.row
  .col-md-12
    .page-title
      %h3
        User Signups -
        =@challenge.challenge_users.count
    %table.table.table-striped
      %thead
        %tr
          %th Join Date
      %tbody
        - @challenge.challenge_users.each do |user|
          %tr
            %td= user.created_at

%br
= link_to 'Back to Challenges', challenges_path
%br

app/views/challenges/edit.html.haml
%h1 Editing challenge
= render 'form'

= link_to 'Show', @challenge

app/views/challenges/index.html.haml
.page-title
  %h1 Challenges

  = link_to 'New Challenge', new_challenge_path, class: 'btn btn-primary'

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Start Date
      %th End Date
      %th Total Offer
      %th Amount raised
      %th enabled
      %th Actions

  %tbody
    - @challenges.each do |challenge|
      %tr
        %td= challenge.name
        %td= challenge.start_date
        %td= challenge.end_date
        %td= challenge.total_offer
        %td= challenge.amount_raised
        %td= challenge.enabled
        %td
          = link_to 'View', challenge_path(challenge)
          |
          = link_to 'Edit', edit_challenge_path(challenge)
          |
          = link_to 'Analytics', challenge_analytics_path(challenge)
          |
          = link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' }

app/views/challenges/new.html.haml
%h1 New challenge
= render 'form'
= link_to 'Back', challenges_path

app/views/challenges/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @challenge.name
%p
  %strong Description:
  = @challenge.description
%p
  %strong Start date:
  = @challenge.start_date
%p
  %strong End date:
  = @challenge.end_date
%p
  %strong Challenge img:
  - if @challenge.challenge_img.exists?
    = image_tag @challenge.challenge_img.url
%p
  %strong Thumb img:
  - if @challenge.img_thumb_url.exists?
    = image_tag @challenge.img_thumb_url.url
%p
  %strong Logo img:
  - if @challenge.logo_url.exists?
    = image_tag @challenge.logo_url.url
%p
%strong Total offer:
= @challenge.total_offer

%br
= link_to 'Back to Challenges', challenges_path
%br

.row
  .col-md-6
    .page-title
      %h2
        Nonprofits
      = form_tag("/challenges/#{@challenge.id}/add_nonprofit", method: 'put', id: 'add-nonprofit', class: 'form-inline') do
        = select_tag 'nonprofit_id', options_for_select(available_nonprofits), prompt: 'Select Nonprofit', class: 'form-control'
        = submit_tag 'Add Nonprofit', class: 'btn btn-primary'

      %table.table.table-striped
        %thead
          %tr
            %th Name
            %th Action
        %tbody
          - @challenge.nonprofits.each do |nonprofit|
            %tr
              %td= nonprofit.name
              %td= link_to 'remove', challenge_remove_nonprofit_path(@challenge, nonprofit), method: :put, 'data-confirm' => "Are you sure you want to remove #{nonprofit.name} from this challenge?"

  .col-md-6
    .page-title
      %h2
        Sponsors
      = form_tag("/challenges/#{@challenge.id}/add_sponsor", method: 'put', id: 'add-sponsor', class: 'form-inline') do
        = select_tag 'sponsor_id', options_for_select(available_sponsors), prompt: 'Select Sponsor', class: 'form-control'
        = submit_tag 'Add Sponsor', class: 'btn btn-primary'

      %table.table.table-striped
        %thead
          %tr
            %th Name
            %th Action
        %tbody
          - @challenge.sponsors.each do |sponsor|
            %tr
              %td= sponsor.name
              %td= link_to 'remove', challenge_remove_sponsor_path(@challenge, sponsor), method: :put, 'data-confirm' => "Are you sure you want to remove #{sponsor.name} from this challenge?"
%hr
.row
  .col-md-12
    .page-title
      %h2 Actions

      = form_tag("/challenges/#{@challenge.id}/action_stubs/new", method: 'get', id: 'new-action', class: 'form-inline') do
        = select_tag "action_type", options_for_select(action_type_collection), class: 'form-control'
        = submit_tag 'Add New Action', class: 'btn btn-primary'

    %table.table.table-striped
      %thead
        %tr
          %th Name
          %th Action Type
          %th

      %tbody
        - @challenge.action_stubs.each do |action|
          %tr
            %td= action.name
            %td= action.as_action_stub_type
            %td
              = link_to 'View', challenge_action_stub_path(@challenge, action)
              |
              = link_to 'Edit', edit_challenge_action_stub_path(@challenge, action)
              |
              = link_to 'Destroy', challenge_action_stub_path(@challenge, action), method: :delete, data: { confirm: 'Are you sure?' }