config/routes.rb
Vervootest2::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "vervoom/home"
  get "vervoom/challenges"
  get "vervoom/users"
  get "vervoom/sponsors"
  get "vervoom/nonprofits"

  resources :roles
  resources :sponsors
  resources :nonprofits

  resources :challenges do
    put '/add_sponsor', to: 'challenges#add_sponsor', as: 'add_sponsor'
    put '/add_nonprofit', to: 'challenges#add_nonprofit', as: 'add_nonprofit'
    put '/remove_sponsor/:id', to: 'challenges#remove_sponsor', as: 'remove_sponsor'
    put '/remove_nonprofit/:id', to: 'challenges#remove_nonprofit', as: 'remove_nonprofit'
    get '/analytics', to: 'challenges#analytics', as: 'analytics'
    get :autocomplete_location_name, :on => :collection
    get :autocomplete_topic_name, :on => :collection

    resources :action_stubs, except: [:index, :create]
    resources :action_scavengers, only: [:create, :update] do
      resources :scavenger_items, except: [:index, :show] do
        put '/add_prereq', to: 'scavenger_items#add_prereq', as: 'add_prereq'
        put '/remove_prereq/:id', to: 'scavenger_items#remove_prereq', as: 'remove_prereq'
        get '/showqr', to: 'scavenger_items#showqr', as: 'showqr'
      end
    end
    resources :action_simpleshares, only: [:create, :update]
  end

  devise_for :users, skip: [:registrations, :passwords]


  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    delete '/signout' => 'devise/sessions#destroy', as: :signout
    get 'users/edit' => 'devise/registrations#edit', :as => 'profile'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users, only: [:index, :new, :show, :create, :destroy]

  root :to => "vervoom#home"
end

app/models/nonprofit.rb
class Nonprofit < ActiveRecord::Base
  has_attached_file :image_full
  has_attached_file  :image_thumb

  has_and_belongs_to_many :challenges
end

app/controllers/nonprofits_controller.rb
class NonprofitsController < ApplicationController
  before_action :set_nonprofit, only: [:show, :edit, :update, :destroy]

  def index
    @nonprofits = Nonprofit.all
  end

  def show
  end

  # GET /nonprofits/new
  def new
    @nonprofit = Nonprofit.new
  end

  # GET /nonprofits/1/edit
  def edit
  end

  def create
    @nonprofit = Nonprofit.new(nonprofit_params)

    respond_to do |format|
      if @nonprofit.save
        format.html { redirect_to @nonprofit, notice: 'Nonprofit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @nonprofit }
      else
        format.html { render action: 'new' }
        format.json { render json: @nonprofit.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @nonprofit.update(nonprofit_params)
        format.html { redirect_to @nonprofit, notice: 'Nonprofit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @nonprofit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @nonprofit.destroy
    respond_to do |format|
      format.html { redirect_to nonprofits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nonprofit
      @nonprofit = Nonprofit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nonprofit_params
      params.require(:nonprofit).permit(:email, :enabled, :name, :address1, :address2, :city, :state, :province, :postal_code, :country, :phone_number, :img_url, :website, :seo_name, :img_thumb_url,:image_full, :image_thumb)
    end
end

app/helpers/nonprofits_helper.rb
module NonprofitsHelper
end

app/views/nonprofits/_form.html.haml
= form_for @nonprofit, :html => { :multipart => true }  do |f|
  - if @nonprofit.errors.any?
    #error_explanation
      %h2
        = pluralize(@nonprofit.errors.count, "error")
        prohibited this nonprofit from being saved:
      %ul
        - @nonprofit.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .field
    = f.label :enabled
    %br/
    = f.check_box :enabled
  .field
    = f.label :image_full
    %br/
    = f.file_field :image_full
  .field
    = f.label :image_thumb
    %br/
    = f.file_field :image_thumb
  .field
    = f.label :address1
    %br/
    = f.text_field :address1
  .field
    = f.label :address2
    %br/
    = f.text_field :address2
  .field
    = f.label :city
    %br/
    = f.text_field :city
  .field
    = f.label :state
    %br/
    = f.text_field :state
  .field
    = f.label :province
    %br/
    = f.text_field :province
  .field
    = f.label :postal_code
    %br/
    = f.text_field :postal_code
  .field
    = f.label :country
    %br/
    = f.text_field :country
  .field
    = f.label :phone_number
    %br/
    = f.text_field :phone_number
  .field
    = f.label :website
    %br/
    = f.text_field :website
  .field
    = f.label :seo_name
    %br/
    = f.text_field :seo_name
  .actions
    = f.submit

app/views/nonprofits/edit.html.haml
%h1 Editing nonprofit
= render 'form'
= link_to 'Show', @nonprofit
|
\#{link_to 'Back', nonprofits_path}

app/views/nonprofits/index.html.haml
.page-title
  %h1 Nonprofits

  = link_to 'New Nonprofit', new_nonprofit_path, class: 'btn btn-primary'

%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Email
      %th Enabled
      %th City
      %th State
      %th Phone number
      %th Website
      %th Actions
  %tbody
    - @nonprofits.each do |nonprofit|
      %tr
        %td= nonprofit.name
        %td= nonprofit.email
        %td= nonprofit.enabled
        %td= nonprofit.city
        %td= nonprofit.state
        %td= nonprofit.phone_number
        %td= nonprofit.website
        %td
          = link_to 'View', nonprofit
          |
          = link_to 'Edit', edit_nonprofit_path(nonprofit)
          |
          = link_to 'Destroy', nonprofit, method: :delete, data: { confirm: 'Are you sure?' }
%br/

app/views/nonprofits/new.html.haml
%h1 New nonprofit
= render 'form'
= link_to 'Back', nonprofits_path

app/views/nonprofits/show.html.haml
%p#notice= notice
%p
  %strong Email:
  = @nonprofit.email
%p
  %strong Enabled:
  = @nonprofit.enabled
%p
  %strong Name:
  = @nonprofit.name
%p
  %strong Thumb img:
  - if @nonprofit.image_thumb.exists?
    = image_tag @nonprofit.image_thumb.url
%p
  %strong Full img:
  - if @nonprofit.image_full.exists?
    = image_tag @nonprofit.image_full.url
%p
  %strong Address1:
  = @nonprofit.address1
%p
  %strong Address2:
  = @nonprofit.address2
%p
  %strong City:
  = @nonprofit.city
%p
  %strong State:
  = @nonprofit.state
%p
  %strong Province:
  = @nonprofit.province
%p
  %strong Postal code:
  = @nonprofit.postal_code
%p
  %strong Country:
  = @nonprofit.country
%p
  %strong Phone number:
  = @nonprofit.phone_number
%p
  %strong Website:
  = @nonprofit.website
%p
  %strong Seo name:
  = @nonprofit.seo_name
= link_to 'Edit', edit_nonprofit_path(@nonprofit)
|
\#{link_to 'Back', nonprofits_path}